// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BiService.proto

package com.bi.biservice;

public final class BiServerService {
  private BiServerService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017BiService.proto\022\tBiService\032\014Common.pro" +
      "to2\234\005\n\tBiService\022@\n\007Install\022\030.BiService." +
      "CommonRequest\032\031.BiService.CommonResponse" +
      "\"\000\022@\n\007StartUp\022\030.BiService.CommonRequest\032" +
      "\031.BiService.CommonResponse\"\000\022A\n\010Register" +
      "\022\030.BiService.CommonRequest\032\031.BiService.C" +
      "ommonResponse\"\000\022>\n\005Login\022\030.BiService.Com" +
      "monRequest\032\031.BiService.CommonResponse\"\000\022" +
      "@\n\007Payment\022\030.BiService.CommonRequest\032\031.B" +
      "iService.CommonResponse\"\000\022@\n\007Economy\022\030.B" +
      "iService.CommonRequest\032\031.BiService.Commo" +
      "nResponse\"\000\022@\n\007AddUser\022\030.BiService.Commo" +
      "nRequest\032\031.BiService.CommonResponse\"\000\022>\n" +
      "\005Quest\022\030.BiService.CommonRequest\032\031.BiSer" +
      "vice.CommonResponse\"\000\022>\n\005Event\022\030.BiServi" +
      "ce.CommonRequest\032\031.BiService.CommonRespo" +
      "nse\"\000\022B\n\tHeartbeat\022\030.BiService.CommonReq" +
      "uest\032\031.BiService.CommonResponse\"\000B%\n\020com" +
      ".bi.biserviceB\017BiServerServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bi.biservice.Common.getDescriptor(),
        });
    com.bi.biservice.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
