// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package com.bi.biservice;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BiService_CommonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BiService_CommonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BiService_CommonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BiService_CommonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Common.proto\022\tBiService\"/\n\rCommonReque" +
      "st\022\r\n\005msgId\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\">\n\016Co" +
      "mmonResponse\022\r\n\005msgId\030\001 \001(\005\022\014\n\004code\030\002 \001(" +
      "\005\022\017\n\007message\030\003 \001(\tB\024\n\020com.bi.biserviceP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BiService_CommonRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BiService_CommonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BiService_CommonRequest_descriptor,
        new java.lang.String[] { "MsgId", "Message", });
    internal_static_BiService_CommonResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BiService_CommonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BiService_CommonResponse_descriptor,
        new java.lang.String[] { "MsgId", "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
