// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package com.bi.biservice;

public interface CommonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BiService.CommonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 msgId = 1;</code>
   * @return The msgId.
   */
  int getMsgId();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
